### ISSUE TITLE
文字选取复制

### ISSUE THREAD

**Issue by theoneee** [bifan-wei/HwTxtReader#10]
现在的弄的是在 
void onTextChanging(float x,float y,String selectText); 
添加一个坐标，
然后   
public void onTextChanging(float x,float y,String selectText) {
                    if(startCopy)
                    {
                        copyX = x;
                        copyY = y;
                        startCopy = false;
                        Log.e("LOG","  copyX = "+copyX+"   copyY = "+copyY);
                    }
            }

只选取第一次的坐标，得到后 
 copyTextWindow.showAsDropDown(mTxtReaderView,(int)copyX,(int)copyY);

这样大概就能显示在选择字段的中间位置。
在
  ClipboardManager copy = (ClipboardManager)
                            getSystemService(Context.CLIPBOARD_SERVICE);
//                    将选取的内容放入剪切板
                    copy.setText(content);
                    copyTextWindow.dismiss();
之后  怎么退出选取模式呢。

**Comment by bifan-wei** [comment]
这确实是个问题，晚上我修改下，提供个方法退出选取模式

**Comment by bifan-wei** [comment]
@theoneee 已添加释放选择模式方法

**Comment by theoneee** [comment]
@bifan-wei  收到~~  谢谢大佬~

**Comment by theoneee** [comment]
那个弹窗位置有啥建议吗。感觉我写的那个不是很好。

**Comment by bifan-wei** [comment]
这个得看具体需求具体设计，我不好说

**Comment by TrebleZ** [comment]
@bifan-wei 需要在文字选中的第一行正上方弹出popwindow,有什么比较好的思路吗

**Comment by TrebleZ** [comment]
好的，谢谢大佬。

**Comment by TrebleZ** [comment]
那个选择字体的滑块不是很灵敏，能优化吗

**Comment by TrebleZ** [comment]
文字选取复制的两个滑块不是很灵敏，能优化吗

**Comment by bifan-wei** [comment]
OK，找个时间再优化优化
