### ISSUE TITLE
loadTxtFile函数和编码格式疑问 请教

### ISSUE THREAD

**Issue by mailxiaoping** [bifan-wei/HwTxtReader#13]
有两个疑问请教:
1loadTxtFile(Context context, String FilePath, String FileName)好像有问题
HwTxtPlayActivity.loadTxtFile(this,"${getExternalStorageDirectory()}/storyReader/末日乐园","第一章灰姑娘的恐惧.txt")访问失败,提示文件不存在
HwTxtPlayActivity.loadTxtFile(this,"${getExternalStorageDirectory()}/storyReader/末日乐园/第一章灰姑娘的恐惧.txt")访问成功

2.如何设置编码,上面的文件是以UTF-8写入的,读取时是乱码
类似file.appendText("somecontent", Charsets.UTF_8)

**Comment by bifan-wei** [comment]
@mailxiaoping 1loadTxtFile应该没有问题，调用是同一个方法。文件编码是通过判断文件识别的，能把你乱码的文件发我邮箱 1198330662@qq.com 测试下么

**Comment by bifan-wei** [comment]
我测试了很多，没发现乱码，可以把文件发我邮箱测试么，1198330662@qq.com

**Comment by TrebleZ** [comment]
已经发给你邮箱了

**Comment by bifan-wei** [comment]
OK，谢谢
