### ISSUE TITLE
翻页刷新有bug

### ISSUE THREAD

**Issue by TrebleZ** [bifan-wei/HwTxtReader#17]
没完全翻页的情况下，再退回，然后再继续翻下一页无法刷新当前页面的内容了

**Comment by bifan-wei** [comment]
请问你用的是哪个版本，V1.3.4版本应该已经修复了这个问题

**Comment by TrebleZ** [comment]
我用的是最新版的V1.3.4,翻页动画效果是滑盖的时候会有这个bug,平移的时候不会，我用了最新版的demo本地运行后选择滑盖的翻页动效后也会有这样的bug

**Comment by TrebleZ** [comment]
效果图我发你邮箱了。。。你可以看下

**Comment by bifan-wei** [comment]
好的感谢

**Comment by bifan-wei** [comment]
我这边三部手机测试没有发现到这个问题，能帮忙把你测试demo的apk与txt文件发我么

**Comment by TrebleZ** [comment]
好的。

**Comment by bifan-wei** [comment]
已更新，问题应该已修复了

**Comment by TrebleZ** [comment]
嗯嗯。解决了，感谢大佬
