### ISSUE TITLE
监听翻书

### ISSUE THREAD

**Issue by TrebleZ** [bifan-wei/HwTxtReader#19]
我这边想添加一个翻书到最后一页的提示，好像没有翻书翻页的监听方法。。。要加在哪里

**Comment by TrebleZ** [comment]
就是滑动到最后一页的时候，然后再去滑动下一页，这个时候提示，“已经是最后一页了”

**Comment by bifan-wei** [comment]
这个也可以，有点点不好加，我晚上看看写个监听器吧

**Comment by bifan-wei** [comment]
可以通过这个方法监听
mTxtReaderView.setOnPageEdgeListener(new IPageEdgeListener() {
    @Override
    public void onCurrentFirstPage() {
    toast("onCurrentFirstPage");
    }

    @Override
    public void onCurrentLastPage() {
    toast("onCurrentLastPage");
    }
    });

**Comment by TrebleZ** [comment]
一般的需求应该是是翻书到最后一页继续往左滑才提醒，已经是最后一页了，所以我在onScroll的方法里面加了一个监听。。。

**Comment by TrebleZ** [comment]
@saljfla 我是这么做的
1、在IPageChangeListener接口中加个方法 
`void onPageChange(boolean isLast);`
2、然后在TxtReaderBaseView的onScroll中实现这个方法
`  /**
     * @param motionEvent motionEvent
     * @param motionEvent1 motionEvent1
     * @param v v
     * @param v1 v1
     * @return
     */
    @Override
    public boolean onScroll(MotionEvent motionEvent, MotionEvent motionEvent1, float v, float v1) {
        pageChangeListener.onPageChange(isLastPage()&&v>0
                && CurrentMode != Mode.PressSelectText
                && CurrentMode != Mode.PressUnSelectText
                && CurrentMode != Mode.SelectMoveForward
                && CurrentMode != Mode.SelectMoveBack
        );//并且向右滑
        return false;
    }`
3、最后就可以愉快的使用了
` textView.setPageChangeListener(object :IPageChangeListener{
            override fun onPageChange(isLast: Boolean) {
                if(isLast){
                    ToastUitls.getToast(this@BookReadActivity,"已经是最后一页了")
                }
            }

            override fun onCurrentPage(progress: Float) {
             
            }

        })`

**Comment by TrebleZ** [comment]
@saljfla 1、在IPageChangeListener接口中加个方法 
void onPageChange(boolean isLast);
2、然后在TxtReaderBaseView的onScroll中实现这个方法
 /**
     * @param motionEvent motionEvent
     * @param motionEvent1 motionEvent1
     * @param v v
     * @param v1 v1
     * @return
     */
    @Override
    public boolean onScroll(MotionEvent motionEvent, MotionEvent motionEvent1, float v, float v1) {
        pageChangeListener.onPageChange(isLastPage()&&v>0
                && CurrentMode != Mode.PressSelectText
                && CurrentMode != Mode.PressUnSelectText
                && CurrentMode != Mode.SelectMoveForward
                && CurrentMode != Mode.SelectMoveBack
        );//并且向右滑
        return false;
    }
3、最后就可以愉快的使用了
textView.setPageChangeListener(object :IPageChangeListener{
            override fun onPageChange(isLast: Boolean) {
                if(isLast){
                    ToastUitls.getToast(this@BookReadActivity,"已经是最后一页了")
                }
            }

            override fun onCurrentPage(progress: Float) {
             
            }

        })

**Comment by saljfla** [comment]
@TrebleZ 多谢大佬
