### ISSUE TITLE
设置字体或者设置颜色后报错。

### ISSUE THREAD

**Issue by PiterPeng** [bifan-wei/HwTxtReader#20]
java.lang.NullPointerException: Attempt to read from field 'int com.bifan.txtreaderlib.main.PageParam.PageWidth' on a null object reference

**Comment by bifan-wei** [comment]
具体是怎么出现的？demo报的错还是自定义写的报错？

**Comment by PiterPeng** [comment]
自定义出现的错误 版本V1.3.4  Android7.0

**Comment by bifan-wei** [comment]
你参考HwTxtPlayActivity看看怎么写，还不行，贴一下你详细代码出来看看

**Comment by PiterPeng** [comment]
加载TXT成功后，调用不了 initWhenLoadDone(); 这个方法。所以导致出现空指针。目前已经把zip包下载下来自己在改HwTxtPlayActivity里面的UI了。。。 @bifan-wei

**Comment by bifan-wei** [comment]
ok，我明白了，下次更新我把那个方法开放为protected~自定义使用出现问题建议参考HwTxtPlayActivity，并不复杂的~
