### ISSUE TITLE
英文不断词 自动换行

### ISSUE THREAD

**Issue by saljfla** [bifan-wei/HwTxtReader#24]
感谢 @bifan-wei 分享代码，本人小白，看楼主是以字符为对象保存的，请问英文小说不断词自动换行，好不好修改啊

**Comment by bifan-wei** [comment]
@saljfla 不断词自动换行，是什么意思，不是很理解

**Comment by saljfla** [comment]
@bifan-wei 加载英文小说，每行显示的最后一个英语单词一半在行尾，一半在下一行行首，被断开了

**Comment by bifan-wei** [comment]
@saljfla  这个有点麻烦，改动会有点大，分页等很多逻辑需要进行调整，不那么容易改

**Comment by saljfla** [comment]
@bifan-wei 好的 谢谢
