### ISSUE TITLE
本人小白一枚。敢问楼主，将小说读出来并且显示在主界面。写在里那个类或者是哪个方法里

### ISSUE THREAD

**Issue by Marypipixia** [bifan-wei/HwTxtReader#25]

**Comment by bifan-wei** [comment]
直接使用我写的界面，可以使用 HwTxtPlayActivity.loadTxtFile(this, FilePath);//传递一个文件路径。
自定义的话，引用TxtReaderView ，然后使用mTxtReaderView.loadTxtFile方法直接加载文件，使用出现问题参考HwTxtPlayActivity就可以了挺详细的。更具体的，请看wiki介绍
