### ISSUE TITLE
请问一下，遇到\n的时候不换行怎么处理的

### ISSUE THREAD

**Issue by liuxinghuao** [bifan-wei/HwTxtReader#26]
请问一下，遇到\n的时候不换行怎么处理的

**Comment by bifan-wei** [comment]
@liuxinghuao 不会对字符单独识别，txt文本里面显示什么就显示什么，你在文本中单独出入\r\n字符保存，也是会显示字符的

**Comment by LuyuchengSTAR** [comment]
我也想问，怎么实现换行呢？

**Comment by mybirthfather** [comment]
> 我也想问，怎么实现换行呢？

你好 你解决了么 我现在也是想换行
