### ISSUE TITLE
想要知道是怎么确定是一页多少个字的

### ISSUE THREAD

**Issue by TrebleZ** [bifan-wei/HwTxtReader#42]
这个库我使用了，但是要是问到是如何实现的感觉还是不太好理解，paragraphindex和chartindex是如何确定进度的啊，然后每个页的字符数量都是确定的吗？

**Comment by bifan-wei** [comment]
文本的每个字符都可以通过paragraphindex（所在的段落位置）与chartindex（在段落的字符位置）来确定，每一页的字符数量都不是固定的，通过计算出来，看字符是否已经填充满一页，这个可以通过paint.breakText计算每行的字符数量，不同的屏幕手机显示的行数是固定的，这样可以计算出每一页的字符数量，paragraphindex和chartindex，可以使知道上一页与下一页的位置以及当前页在全文本的进度。

**Comment by TrebleZ** [comment]
@bifan-wei 好的。谢谢了
