### ISSUE TITLE
TxtReaderView的一点小问题

### ISSUE THREAD

**Issue by NecoJack** [bifan-wei/HwTxtReader#44]
大佬
使用TxtReaderView的setStyle的时候改变背景颜色为黑色 字体为白色时 实际上背景变成蓝色 字体颜色也没有变化 
在使用setTextSize设置字体大小时也没有变化
不知道什么情况

**Comment by bifan-wei** [comment]
单独使用readerview的话参考hwtxtplayactivity的使用方式

**Comment by NecoJack** [comment]
大佬 
我在hwtxtplayactivity的基础上添加了另外一个底部的bar 其中包括一个夜间模式的按钮

我把hwtxtplayactivity 里   StyleChangeClickListener中的 
            mTxtReaderView.setStyle(BgColor, TextColor);
            mTopDecoration.setBackgroundColor(BgColor);
            mBottomDecoration.setBackgroundColor(BgColor);
            if (mChapterListPop != null) {
                mChapterListPop.setBackGroundColor(BgColor);
            }
这段单独抽出来放到按钮监听事件中使用改变mTxtReaderView等的背景颜色  
 
但mTxtReaderView还是一改变背景颜色就变蓝屏 
mChapterListPop的背景颜色也是变得很奇怪 有点偏紫色

mTopDecoration和mBottomDecoration颜色正常
字体颜色也可以改变
