### ISSUE TITLE
你好，可以分享一下每一章节分页加载的思路吗，每章节都是请求网络

### ISSUE THREAD

**Issue by cenjunlei** [bifan-wei/HwTxtReader#47]
看了一下代码，关键代码似乎是DrawPrepareTask。

**Comment by bifan-wei** [comment]
这个需要自己自定义使用那个txtreaderview~它有直接加载字符串的方法，获取章节数据回来直接加载进去应该就可以了

**Comment by githubzoujiayun** [comment]
楼主，不行哈， 第一章用字符串加载loadstr后显示了  第二张loadstr后就错乱了 有解决方案吗

**Comment by bifan-wei** [comment]
> 楼主，不行哈， 第一章用字符串加载loadstr后显示了 第二张loadstr后就错乱了 有解决方案吗

试一试动态添加TxtReaderView，每一章就用一个新的TxtReaderView加载
