### ISSUE TITLE
如何设置文字的排列方向和章节列表

### ISSUE THREAD

**Issue by xiaochao** [bifan-wei/HwTxtReader#50]
使用自定义TxtReaderView时，默认的文字排列是竖向的，如何设置成横向排列的。
使用自定义TxtReaderView时，如何设置章节列表？因为我是网络获取的小说内容，可以获取到所有章节，然后获取制定章节的内容。

**Comment by xiaochao** [comment]
使用loadTxtFile函数时，txt文件里，章节名应该怎么写，能保证自动识别到章节名称。

**Comment by bifan-wei** [comment]
txt文件的话，章节数据是会在读取数据时自动匹配识别，加载完可以拿到章节数据如果匹配到有数据的话
