### ISSUE TITLE
文字添加下划线，可以实现动态添加么，还是下划线的颜色 可以设置么？

### ISSUE THREAD

**Issue by deilsky** [bifan-wei/HwTxtReader#52]
文字添加下划线，可以实现动态添加么，还是下划线的颜色 可以设置么？
现在在您的基础之上 加入了下划线功能；请问 能实现动态添加下划线 或者 动态改变某个文字？

**Comment by bifan-wei** [comment]
不是很明白你的意思啊，如果是把目前的长按选择然后滑动选择的显示改为下划线选中的话，肯定是可以的啊，但是需要自己改了

**Comment by deilsky** [comment]
不是选中样式，是给指定文字添加带有下划线的文字样式。

**Comment by bifan-wei** [comment]
理论可以的，你去看看txtchar那个怎么写，仿照数字跟英文字符改变颜色的功能，改改应该可以，要匹配你需要的字符

**Comment by bifan-wei** [comment]
这个目前看有点麻烦

**Comment by deilsky** [comment]
确实麻烦，您有什么好的思路么？

**Comment by bifan-wei** [comment]
你去看我那个长按选择功能的demo，仿照上面自己写个view更快点，目前这个view比较复杂的了，不是很好弄
