### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by DecentSavage** [bifan-wei/HwTxtReader#55]
楼主，为什么，继承HwTxtPlayActivity后，TxtReaderView加载文件后，有个toast 跳出来 显示文件不存在

**Comment by bifan-wei** [comment]
确定下你传进去的文件路径是正确的么，该文件是否存在

**Comment by DecentSavage** [comment]
跳出toast之后 又跳到正常的文字阅读界面

**Comment by bifan-wei** [comment]
不继承，直接使用HwTxtPlayActivity会这样么

**Comment by DecentSavage** [comment]
不继承的话 不会

**Comment by bifan-wei** [comment]
可以贴下你继承的activity代码看看么

**Comment by DecentSavage** [comment]
public class ReadBookActivity extends HwTxtPlayActivity{

    private TxtReaderView readerView;
    private ReadingFragment fm;
    private FragmentManager manager;
    private FragmentTransaction transaction;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //去除标题栏,继承了HwTxtPlayActivity，常用去标题方法导致程序奔溃
        ActionBar actionBar = getSupportActionBar();
        actionBar.hide();
        //supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
        //进入activity，先进入全屏状态
        WindowManager.LayoutParams params = getWindow().getAttributes();
        params.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
        getWindow().setAttributes(params);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        setContentView(R.layout.activity_read_book);
        readerView=findViewById(R.id.readerview);
        initview();
    }

    private void initview(){
            String txtFilePath = getIntent().getStringExtra("txtFilePath");//获取传进来的文本路径
            TxtConfig.saveIsOnVerticalPageMode(this,false);//设置文字排版方式，默认垂直
//        HwTxtPlayActivity.loadTxtFile(this, txtFilePath);//使用第三方API接口播放Txt文件
            //阅读界面加载
            readerView.loadTxtFile(txtFilePath, new ILoadListener() {
                @Override
                public void onSuccess() {
                    //加载成功回调
                    initWhenLoadDone();
                    //只能在里面调用
                    readerView.setTextSize(50);
                }

                @Override
                public void onFail(TxtMsg txtMsg) {
                    //加载失败回调
                }

                @Override
                public void onMessage(String message) {
                    //加载过程信息回调
                }
            });
    }

**Comment by DecentSavage** [comment]
public class ReadBookActivity extends HwTxtPlayActivity{

    private TxtReaderView readerView;
    private ReadingFragment fm;
    private FragmentManager manager;
    private FragmentTransaction transaction;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //去除标题栏,继承了HwTxtPlayActivity，常用去标题方法导致程序奔溃
        ActionBar actionBar = getSupportActionBar();
        actionBar.hide();
        //supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
        //进入activity，先进入全屏状态
        WindowManager.LayoutParams params = getWindow().getAttributes();
        params.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
        getWindow().setAttributes(params);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        setContentView(R.layout.activity_read_book);
        readerView=findViewById(R.id.readerview);
        initview();
        hear();
//        manager=getFragmentManager();
//        transaction=manager.beginTransaction();
//
//        fm=new ReadingFragment();
//        transaction.replace(R.id.reading_page,fm);
//        transaction.commit();
    }

    private void initview(){
            String txtFilePath = getIntent().getStringExtra("txtFilePath");//获取传进来的文本路径
            TxtConfig.saveIsOnVerticalPageMode(this,false);//设置文字排版方式，默认垂直
//        HwTxtPlayActivity.loadTxtFile(this, txtFilePath);//使用第三方API接口播放Txt文件
            //阅读界面加载
            readerView.loadTxtFile(txtFilePath, new ILoadListener() {
                @Override
                public void onSuccess() {
                    //加载成功回调
                    initWhenLoadDone();
                    //只能在里面调用
                    readerView.setTextSize(50);
                }

                @Override
                public void onFail(TxtMsg txtMsg) {
                    //加载失败回调
                }

                @Override
                public void onMessage(String message) {
                    //加载过程信息回调
                }
            });
    }

**Comment by DecentSavage** [comment]
mTxtReaderView.setTextSize(textSize);似乎是只能在public void onSuccess() {}里面调用，在其它地方调用，程序会崩溃

**Comment by bifan-wei** [comment]
你这是重新写啊的，你直接重写下面的方法就好啦，
 protected void loadFile() {
       FilePath = 你的文件路径；
      super.loadfile();
    }
其他不要动的啊，布局文件都不用动，onCreate改成这样：
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
      TxtConfig.saveIsOnVerticalPageMode(this,false);//设置文字排版方式，默认垂直
        super.onCreate(savedInstanceState);
        这里进行的其他想要的初始化操作
    }

加载成功后进行其他操作，重写onLoadDataSuccess：
protected void onLoadDataSuccess() {
    FileName = 你的书名
     super.onLoadDataSuccess();
   下面进行你其他业务加载成功后操作
    }
类似其他，你看看HwTxtPlayActivity代码，直接重写方法就可以了，这样比较简单，实在满足不了，仿照HwTxtPlayActivity重新写activity

**Comment by DecentSavage** [comment]
楼主  我想改一些阅读界面的视图效果，请问下面这些R.id.~是在那个目录下查看的，还有 下面的这些组件是什么？ 麻烦了
protected void init() {
        mHandler = new Handler();
        mChapterMsgView = findViewById(R.id.activity_hwtxtplay_chapter_msg);
        mChapterMsgName = (TextView) findViewById(R.id.chapter_name);
        mChapterMsgProgress = (TextView) findViewById(R.id.charpter_progress);
        mTopDecoration = findViewById(R.id.activity_hwtxtplay_top);
        mBottomDecoration = findViewById(R.id.activity_hwtxtplay_bottom);
        mTxtReaderView = (TxtReaderView) findViewById(R.id.activity_hwtxtplay_readerView);
        mChapterNameText = (TextView) findViewById(R.id.activity_hwtxtplay_chaptername);
        mChapterMenuText = (TextView) findViewById(R.id.activity_hwtxtplay_chapter_menutext);
        mProgressText = (TextView) findViewById(R.id.activity_hwtxtplay_progress_text);
        mSettingText = (TextView) findViewById(R.id.activity_hwtxtplay_setting_text);
        mTopMenu = findViewById(R.id.activity_hwtxtplay_menu_top);
        mBottomMenu = findViewById(R.id.activity_hwtxtplay_menu_bottom);
        mCoverView = findViewById(R.id.activity_hwtxtplay_cover);
        ClipboardView = findViewById(R.id.activity_hwtxtplay_Clipboar);
        mSelectedText = (TextView) findViewById(R.id.activity_hwtxtplay_selected_text);

        mMenuHolder.mTitle = (TextView) findViewById(R.id.txtreadr_menu_title);
        mMenuHolder.mPreChapter = (TextView) findViewById(R.id.txtreadr_menu_chapter_pre);
        mMenuHolder.mNextChapter = (TextView) findViewById(R.id.txtreadr_menu_chapter_next);
        mMenuHolder.mSeekBar = (SeekBar) findViewById(R.id.txtreadr_menu_seekbar);
        mMenuHolder.mTextSizeDel = findViewById(R.id.txtreadr_menu_textsize_del);
        mMenuHolder.mTextSize = (TextView) findViewById(R.id.txtreadr_menu_textsize);
        mMenuHolder.mTextSizeAdd = findViewById(R.id.txtreadr_menu_textsize_add);
        mMenuHolder.mBoldSelectedLayout = findViewById(R.id.txtreadr_menu_textsetting1_bold);
        mMenuHolder.mNormalSelectedLayout = findViewById(R.id.txtreadr_menu_textsetting1_normal);
        mMenuHolder.mCoverSelectedLayout = findViewById(R.id.txtreadr_menu_textsetting2_cover);
        mMenuHolder.mTranslateSelectedLayout = findViewById(R.id.txtreadr_menu_textsetting2_translate);

        mMenuHolder.mStyle1 = findViewById(R.id.hwtxtreader_menu_style1);
        mMenuHolder.mStyle2 = findViewById(R.id.hwtxtreader_menu_style2);
        mMenuHolder.mStyle3 = findViewById(R.id.hwtxtreader_menu_style3);
        mMenuHolder.mStyle4 = findViewById(R.id.hwtxtreader_menu_style4);
        mMenuHolder.mStyle5 = findViewById(R.id.hwtxtreader_menu_style5);
    }

    private final int[] StyleTextColors = new int[]{
            Color.parseColor("#4a453a"),
            Color.parseColor("#505550"),
            Color.parseColor("#453e33"),
            Color.parseColor("#8f8e88"),
            Color.parseColor("#27576c")
    };

**Comment by bifan-wei** [comment]
hwtxtreaderlib里面的布局文件啊，兄弟，你是刚学Android的么，组件的功能，命名应该描述的还算清楚啊。如果你改要界面样式的话，不要直接依赖，把hwtxtreaderlib下载下来依赖到你的项目，直接改源码，或者直接使用TxtReaderView仿照HwTxtPlayActivity，TxtReaderView使用可以看看wiki教程

**Comment by DecentSavage** [comment]
楼主 不好意思 我的确刚学android不久 是学生

**Comment by DecentSavage** [comment]
楼主，是我太笨了。最后一个问题  按照你之前教我的 重写loadFile()和onLoadDataSuccess()之后，阅读界面中改变字体大小的监听、改变字体加粗、滑动方式和和改变颜色的监听没有生效诶。

![image](https://user-images.githubusercontent.com/44968153/50340087-76cc4100-0554-11e9-9c83-32449095a754.png)

**Comment by bifan-wei** [comment]
把你代码贴全看看

**Comment by DecentSavage** [comment]
public class ReadBookActivity extends HwTxtPlayActivity {

    private  String txtFilePath,txtFileName;


    @Override
    protected void onCreate(Bundle savedInstanceState) {

        //加载方式
        TxtConfig.saveIsOnVerticalPageMode(this,false);
        super.onCreate(savedInstanceState);

        //去除标题栏,继承了HwTxtPlayActivity，常用去标题方法导致程序奔溃
        ActionBar actionBar = getSupportActionBar();
        actionBar.hide();
        //进入activity，先进入全屏状态
        WindowManager.LayoutParams params = getWindow().getAttributes();
        params.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
        getWindow().setAttributes(params);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);

    }


    //方法的重写，书的路径
    protected void loadFile() {
        txtFilePath = getIntent().getStringExtra("txtFilePath");//获取传进来的文本路径
        FilePath=txtFilePath;
        super.loadFile();
    }
    //方法的重写，书名
    protected void onLoadDataSuccess() {
        txtFileName = getIntent().getStringExtra("txtFileName");//获取传进来的文本路径
        FileName=txtFileName;
        super.onLoadDataSuccess();
        //下面进行你其他业务加载成功后操作
    }
    
}

**Comment by bifan-wei** [comment]
奇怪，看代码似乎没问题，你先把onCreate的方法注释掉，先看看这样行不行，标题栏的问题暂时我们先不管

**Comment by DecentSavage** [comment]
没用诶

**Comment by bifan-wei** [comment]
我试了下，原来是有个判断没有没有重写，代码这样写：
public class TestReaderActivity extends HwTxtPlayActivity{
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        TxtConfig.saveIsOnVerticalPageMode(this,false);//设置文字排版方式，默认垂直
        super.onCreate(savedInstanceState);
    }

    @Override
    protected void onLoadDataSuccess() {
        FileName= getIntent().getStringExtra("txtFileName");//获取传进来的文本路径
        super.onLoadDataSuccess();
    }

    @Override
    protected void loadFile() {
        FilePath = getIntent().getStringExtra("txtFilePath");//获取传进来的文本路径
        FileExist = true;//这个是原来判断文件文件是否存在，文件不存在，不允许操作菜单的
        super.loadFile();
    }
}
主题全屏这样写：
<activity android:name=".TestReaderActivity"  android:theme="@style/HwTxtFullScreen"/>

调用：
                Intent intent = new Intent();
                intent.setClass(this,TestReaderActivity.class);
                intent.putExtra("txtFilePath",FilePath);
                intent.putExtra("txtFileName","testName");
                startActivity(intent);

**Comment by bifan-wei** [comment]
全屏的话，不需要操作actionBar,这样就行了：
<activity android:name=".TestReaderActivity"  android:theme="@style/HwTxtFullScreen"/>

**Comment by bifan-wei** [comment]
全屏的话，不需要操作actionBar,这样就行了：
```java
<activity android:name=".TestReaderActivity"  android:theme="@style/HwTxtFullScreen"/>
```

**Comment by bifan-wei** [comment]
我试了下，原来是有个判断没有没有重写，代码这样写：
```java
public class TestReaderActivity extends HwTxtPlayActivity{
@override
protected void onCreate(@nullable Bundle savedInstanceState) {
TxtConfig.saveIsOnVerticalPageMode(this,false);//设置文字排版方式，默认垂直
super.onCreate(savedInstanceState);
}

@Override
protected void onLoadDataSuccess() {
    FileName= getIntent().getStringExtra("txtFileName");//获取传进来的文本路径
    super.onLoadDataSuccess();
}

@Override
protected void loadFile() {
    FilePath = getIntent().getStringExtra("txtFilePath");//获取传进来的文本路径
    FileExist = true;//这个是原来判断文件文件是否存在，文件不存在，不允许操作菜单的
    super.loadFile();
}
}
```

调用：
```java
Intent intent = new Intent();
intent.setClass(this,TestReaderActivity.class);
intent.putExtra("txtFilePath",FilePath);
intent.putExtra("txtFileName","testName");
startActivity(intent);
```

**Comment by DecentSavage** [comment]
感谢 楼主
