### ISSUE TITLE
退回首页时有几率遇到的问题

### ISSUE THREAD

**Issue by narakai** [bifan-wei/HwTxtReader#59]
退回首页时有几率遇到还能往前翻页，并且百分比计算和第一次不一样。比如第一次第一页是27%，翻到最后返回的时候变成28%，编码是shiftjis

**Comment by narakai** [comment]
补充下，发现原因是第一次返回的时候，首页第一行没了

**Comment by bifan-wei** [comment]
> 退回首页时有几率遇到还能往前翻页，并且百分比计算和第一次不一样。比如第一次第一页是27%，翻到最后返回的时候变成28%，编码是shiftjis

是这样的，有时候在中间进度往前翻页，如果有调整过字体大小或者其他，最后翻到第一页是，可能第一页的数据不是满页数据，比如回翻到第一页，从第二页的开始数据往前计算第一页的数据，这时发现第一页的数据只剩下3行，为了解决这种不好看的情况，会判断判断到首页不是满页时，首页数据会重置，从头开始拿数据，这时可能发现两次进度不大一样

**Comment by narakai** [comment]
明白了 谢谢解答

**Comment by githubzoujiayun** [comment]
还有一个问题 请问支持多国家语言的小说吗 如英文，印度等

**Comment by bifan-wei** [comment]
> 还有一个问题 请问支持多国家语言的小说吗 如英文，印度等

这个跟语言无关，只要是文本的都行
