### ISSUE TITLE
如何获取当前页的文本数据

### ISSUE THREAD

**Issue by narakai** [bifan-wei/HwTxtReader#60]
请教下如何获取当前页的文本数据，试了getTxtReaderContext().getPageData()里好像没有找到？

**Comment by bifan-wei** [comment]
已更新到wiki

//获取当前也数据，MidPage:当前页  FirstPage：上一页，LastPage：下一页。
        IPage currentPage = mTxtReaderView.getTxtReaderContext().getPageData().MidPage();
        //获取当前也所有行数据
        List<ITxtLine> lines = currentPage.getLines();
        //获取第一行数据字符串
        ITxtLine firstLine = lines.get(0);
        String firstLineStr = firstLine.getLineStr();
        //页数据可以通过行数据拼接起来

**Comment by narakai** [comment]
谢谢，虽然我也在源码找到了，还是更新下大家都知道比较好
