### ISSUE TITLE
楼主 调用loadText()方法的时候 文字不会换行，具体看描述

### ISSUE THREAD

**Issue by liuwen370494581** [bifan-wei/HwTxtReader#61]
mTxtReadView.loadText(“这是测试\n这是测试\n\这是测试\n” new ILoadListener()）
我在测试文字也加了\n 换行 

发现呈现出来的还是不会换行，有什么方法可以换行 不然 真的太密集了，看小说看的头都大了。

**Comment by bifan-wei** [comment]
这个目前是不处理换行符的哦，因为本来是处理txt文件的，段落自动换行，可以设置段落间间距，不是专门处理text的，你可以这样折中处理，把你要显示的小说处理好格式比如换好行放在文件中，然后加载播放这个txt小说文件

**Comment by liuwen370494581** [comment]
怎么设置段落间距？？我试着加空格是可以的

**Comment by bifan-wei** [comment]
看看wiki,我记得有写
