### ISSUE TITLE
运行在28以上的设备报错

### ISSUE THREAD

**Issue by Dizner** [bifan-wei/HwTxtReader#65]
这是参考资料https://blog.csdn.net/shanshan_1117/article/details/85097487

**Comment by DreamMemory001** [comment]
必须是绝对路径吗！？可以是网络路径吗？

**Comment by bifan-wei** [comment]
这个应该已修复了

**Comment by Dizner** [comment]
@bifan-wei  2.1.1的版本还是未修复的状态

**Comment by bifan-wei** [comment]
用V2.2试一试

**Comment by Dizner** [comment]
@bifan-wei 好了，运行在Android Q上没有问题，非常感谢

**Comment by zhijing657** [comment]
非常感谢
