### ISSUE TITLE
连文本横向显示的说明都没有。默认是竖着显示 你有见过竖的小说吗？

### ISSUE THREAD

**Issue by sd3970566** [bifan-wei/HwTxtReader#67]
连文本横向显示的说明都没有。默认是竖着显示 你有见过竖的小说吗？

**Comment by bifan-wei** [comment]
TxtConfig.saveIsOnVerticalPageMode(this,false);
            FilePath = mEditText.getText().toString().trim();
            if (TextUtils.isEmpty(FilePath) || !(new File(FilePath)).exists()) {
                toast("文件不存在");
            } else {
                HwTxtPlayActivity.loadTxtFile(this, FilePath);
            }
请看demo
