### ISSUE TITLE
怎么返回上一章直接显示上一章的最后一页

### ISSUE THREAD

**Issue by aysw7331447** [bifan-wei/HwTxtReader#68]
我的章节内容都是动态获取的，我播放字符串，但是显示上一章，想让显示最后一页为当前页，这个怎么弄

**Comment by bifan-wei** [comment]
这个不好实现，或者试一试加载上一章时把进度设置到接近100%。。。或者把章节全下下来，把存成一本书加载？

**Comment by aysw7331447** [comment]
> 这个不好实现，或者试一试加载上一章时把进度设置到接近100%。。。或者把章节全下下来，把存成一本书加载？

我把调用这个方法设置public void loadFromProgress(float progress) 为99.99，好像也没作用

**Comment by bifan-wei** [comment]
你要等你的章节数据加载完，再调这个方法 loadFromProgress(float progress) 为99.99，效果类似于demo apk的这种操作：加载完这章数据显示后，拖动菜单seekbar到99%进度。理论上应该可以

**Comment by bifan-wei** [comment]
可以参考HwTxtPlayActivity 按照你的业务重写下里面的逻辑

**Comment by wenwenwen888** [comment]
@aysw7331447 老哥请问最后实现了吗？
