### ISSUE TITLE
请问 ，修改英文和数字颜色代码在哪里

### ISSUE THREAD

**Issue by zenweifeng** [bifan-wei/HwTxtReader#7]
hi，你好，感谢分享源码！我是小白一枚，想修改下特定文字的样式，但是找不到你项目中关于修改英文和数字颜色的代码，请问下这部分代码在哪里？(位置越具体越好)

**Comment by bifan-wei** [comment]
@zenweifeng  目前可以去bean包下面NumChar 与EnChar类里面修改颜色

**Comment by zenweifeng** [comment]
好的，谢谢

**Comment by bifan-wei** [comment]
V1.3.1版本起，可以通过EnChar.DefaultTextColor   = color 修改英文字符颜色，NumChar .DefaultTextColor   = color 修改数字文字颜色
