### ISSUE TITLE
关于章节名和目录显示问题

### ISSUE THREAD

**Issue by yong396040003** [bifan-wei/HwTxtReader#71]
你好，我想请问一下，默认界面关于章节名和目录是怎么实现的？

**Comment by bifan-wei** [comment]
啥意思，不是很理解？

**Comment by yong396040003** [comment]
我用了一下，发现整个软件是打开一个文件然后根据分隔符区分章节的，但是现在的问题是，一本小说应该不会将所有的章节都保存到一个文件，我的就是根据不同文件来区分章节的，那么这样的话，打开一个文件，那么目录页就只有一章的目录了。请问这有办法解决了。

**Comment by bifan-wei** [comment]
目前绝大多数txt小说都是整本的呀，一本书包括很多章节。如果你要这样做的话，就自定义吧，自己保存章节数据，打开一个章节就打开一个文件
