### ISSUE TITLE
加入自定义View

### ISSUE THREAD

**Issue by CrazyShado** [bifan-wei/HwTxtReader#74]
群主，有没有考虑过加入自定义view呢，比如封面，广告之类的，当前是通过两个bitmap实现的，如果换成两个view有没有思路呢

**Comment by bifan-wei** [comment]
你自己自定义就可以做到了，默认的activity还是纯净版。

**Comment by caochongsheng** [comment]
请问 有没有考虑过加入自定义view呢  如何实现 大神可以加上吗

**Comment by CrazyShado** [comment]
> activity

默认增加自定义view的话，视频之类的如何支持呢，包括翻页的时候如何更好的跟随动画翻页了

**Comment by bifan-wei** [comment]
单纯

**Comment by CrazyShado** [comment]
这块如果有方案的话，可以付费的
