### ISSUE TITLE
添加章节

### ISSUE THREAD

**Issue by lishangwl** [bifan-wei/HwTxtReader#79]
如何添加章节？demo里没有

**Comment by bifan-wei** [comment]
> 如何添加章节？demo里没有

请参考wiki中的  TxtReaderView使用教程

**Comment by lishangwl** [comment]
> > 如何添加章节？demo里没有
> 
> 请参考wiki中的 TxtReaderView使用教程

好的谢谢

**Comment by lishangwl** [comment]
> > 如何添加章节？demo里没有
> 
> 请参考wiki中的 TxtReaderView使用教程

wiki中的 TxtReaderView使用教程中没有添加章节，大佬可否把代码贴出来看一看

**Comment by lishangwl** [comment]
IChapter chapter = new IChapter() {
            @Override
            public int getIndex() {
                return 0;
            }

            @Override
            public int getStartParagraphIndex() {
                return 0;
            }

            @Override
            public int getEndParagraphIndex() {
                return 0;
            }

            @Override
            public int getStartCharIndex() {
                return 0;
            }

            @Override
            public int getEndCharIndex() {
                return 0;
            }

            @Override
            public int getStartIndex() {
                return 0;
            }

            @Override
            public String getTitle() {
                return "第一章";
            }

            @Override
            public void setStartParagraphIndex(int index) {

            }

            @Override
            public void setEndParagraphIndex(int index) {

            }
        };
        List<IChapter> chapters = new ArrayList<>();
        chapters.add(chapter);
        mTxtReaderView.setChapters(chapters);

**Comment by bifan-wei** [comment]
> > > 如何添加章节？demo里没有
> > 
> > 
> > 请参考wiki中的 TxtReaderView使用教程
> 
> wiki中的 TxtReaderView使用教程中没有添加章节，大佬可否把代码贴出来看一看
你为什么要手动添加章节呢，章节是读取文件时识别出来的，要关联具体的章节的开始位置，这样加是不行的

**Comment by bifan-wei** [comment]
现在只有获取到识别出来的章节信息，不能添加章节信息，不然章节跳转时关联不上去。如果你已经有没一章的数据了，可以外部封装一下，使用打开字符串的方式加载数据，自己做章节关联试一试

**Comment by lishangwl** [comment]
> 现在只有获取到识别出来的章节信息，不能添加章节信息，不然章节跳转时关联不上去。如果你已经有没一章的数据了，可以外部封装一下，使用打开字符串的方式加载数据，自己做章节关联试一试

大佬可否给我看看章节信息是什么样的？

**Comment by lishangwl** [comment]
> > 现在只有获取到识别出来的章节信息，不能添加章节信息，不然章节跳转时关联不上去。如果你已经有没一章的数据了，可以外部封装一下，使用打开字符串的方式加载数据，自己做章节关联试一试
> 
> 大佬可否给我看看章节信息是什么样的？

我的字符串文本应该是什么格式？

**Comment by bifan-wei** [comment]
获取章节信息：
List<IChapter> mChapters = mTxtReaderView.getChapters();//获取所有章节
  IChapter currentChapter = mTxtReaderView.getCurrentChapter();//获取当前页章节


以字符串形式加载数据：
public void loadStr(View view) {
        if (Permit) {
            String str = mEditText.getText().toString();
            if (TextUtils.isEmpty(str)) {
                toast("输入为空字符");
            } else {
                HwTxtPlayActivity.loadStr(this, str);
            }
        }
    }
你自己存每个章节的字符串，打开每个章节数据通过loadStr加载

**Comment by githubzoujiayun** [comment]
你好 请问如何动态加载章节数据，比如小说有1000章，打开阅读器加载第一章，看完后再请求网络加载下一章，望回复，谢谢

**Comment by lishangwl** [comment]
> 你好 请问如何动态加载章节数据，比如小说有1000章，打开阅读器加载第一章，看完后再请求网络加载下一章，望回复，谢谢

这个框架加载txt文件（完整小说）是非常完美的，但是加载string我感觉是不行的，我已经没有用这个库了
换了https://github.com/glongdev/Reader

**Comment by githubzoujiayun** [comment]
你好 新的你有集成好模块吗 麻烦发我一份 急用





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bifan-wei/HwTxtReader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 晚上9:29
收件人:&nbsp;"bifan-wei/HwTxtReader"<HwTxtReader@noreply.github.com&gt;;
抄送:&nbsp;"邹家运"<974454738@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bifan-wei/HwTxtReader] 添加章节 (#79)





  
你好 请问如何动态加载章节数据，比如小说有1000章，打开阅读器加载第一章，看完后再请求网络加载下一章，望回复，谢谢
  
这个框架加载txt文件（完整小说）是非常完美的，但是加载string我感觉是不行的，我已经没有用这个库了
 换了https://github.com/glongdev/Reader

**Comment by githubzoujiayun** [comment]
你好 已经看到模块了， 不晓得这个符合我的要求不，我的需要点击文字选中后要处理





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "bifan-wei/HwTxtReader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 晚上9:29
收件人:&nbsp;"bifan-wei/HwTxtReader"<HwTxtReader@noreply.github.com&gt;;
抄送:&nbsp;"邹家运"<974454738@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bifan-wei/HwTxtReader] 添加章节 (#79)





  
你好 请问如何动态加载章节数据，比如小说有1000章，打开阅读器加载第一章，看完后再请求网络加载下一章，望回复，谢谢
  
这个框架加载txt文件（完整小说）是非常完美的，但是加载string我感觉是不行的，我已经没有用这个库了
 换了https://github.com/glongdev/Reader

**Comment by lishangwl** [comment]
> 你好 已经看到模块了， 不晓得这个符合我的要求不，我的需要点击文字选中后要处理
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "bifan-wei/HwTxtReader" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月24日(星期天) 晚上9:29 收件人:&nbsp;"bifan-wei/HwTxtReader"<HwTxtReader@noreply.github.com&gt;; 抄送:&nbsp;"邹家运"<974454738@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [bifan-wei/HwTxtReader] 添加章节 (#79) 你好 请问如何动态加载章节数据，比如小说有1000章，打开阅读器加载第一章，看完后再请求网络加载下一章，望回复，谢谢 这个框架加载txt文件（完整小说）是非常完美的，但是加载string我感觉是不行的，我已经没有用这个库了 换了https://github.com/glongdev/Reader — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

额，你看一下文档和demo吧，我都是下载demo改的
