### ISSUE TITLE
怎么直接放String啊

### ISSUE THREAD

**Issue by theoneee** [bifan-wei/HwTxtReader#8]
不是text，直接放String

**Comment by bifan-wei** [comment]
@theoneee 现在是直接传一个文件不能直接传字符串，后面我改下加个接口吧

**Comment by theoneee** [comment]
@bifan-wei  非常感谢 。我看里面读取文件之后是 readerContext.setFileMsg(fileMsg);   也就是怎么把String转换成 fileMsg 是吗？

**Comment by bifan-wei** [comment]
@theoneee 那个是用来记录文件信息的，fileMsg.FileCode是保存文件编码，现在逻辑是：读取文件信息---》加载文件得到字符串---》其他处理，你现在是想把这两步跳过，所以逻辑会有变动，我只好加个接口，判断一下，如果是字符串就跳过这两步

**Comment by theoneee** [comment]
@bifan-wei 好的。辛苦了。大佬~

**Comment by bifan-wei** [comment]
@theoneee  记得start支持下哈哈，有啥问题尽管提，想做好这个库

**Comment by theoneee** [comment]
@bifan-wei 我把你的这个代码复制了过来界面改了一些。哈哈。到时候效果给你看下。如果觉得可以你就加进去。哈哈

**Comment by bifan-wei** [comment]
@theoneee 哈哈，可以的啊

**Comment by theoneee** [comment]
最近在做项目的朋友圈。都忘记这个了。大哥那个接口写好了吗。

**Comment by bifan-wei** [comment]
@theoneee 最近忙着项目验收，星期天我弄一下吧

**Comment by theoneee** [comment]
好的好的。感谢大佬·~~~ 辛苦了
