### ISSUE TITLE
选择文件--最近使用过的文件 没东西啊

### ISSUE THREAD

**Issue by sbdlhl** [bifan-wei/HwTxtReader#84]
Android Studio 3.5.2使用代码正常，安装到真机Android 10手机上，基本功能都正常。就是每次都要点“选择文件”--“文件管理”--找到文件才行，为啥**最近打开的文件名不能保存**呢？（打开过的文件阅读位置是可以保存的，只是带路径的文件名不行）

**Comment by bifan-wei** [comment]
这个是系统自带的文件选择器，要用这个的话需要自己额外对接了
