### ISSUE TITLE
Failed to resolve: com.github.bifan-wei:HwTxtReader:V2.2

### ISSUE THREAD

**Issue by young03600** [bifan-wei/HwTxtReader#89]
不好意思
試了很久還是無法正常build
請問一下 這樣該如何解決?

**Comment by bifan-wei** [comment]
您好我是黄威，你的邮件我已经收到！（这是来自QQ邮箱的自动回复邮件。）

**Comment by bifan-wei** [comment]
> 不好意思 試了很久還是無法正常build 請問一下 這樣該如何解決?

不知道你具体是什么原因，你这样问太模糊了。确保build时网络没问题，或者直接使用implementation方式引入使用

**Comment by young03600** [comment]
> > 不好意思 試了很久還是無法正常build 請問一下 這樣該如何解決?
> 
> 不知道你具体是什么原因，你这样问太模糊了。确保build时网络没问题，或者直接使用implementation方式引入使用

引入方式是依照wiki中所寫的方法引入的
build的時候確定網路沒問題

以下是gradle file

     
      
      // Top-level build file where you can add configuration options common to all sub-projects/modules.
    buildscript {
        repositories {
            google()
            mavenCentral()
            maven { url'https://jitpack.io' }
       }
      dependencies {
          classpath 'com.android.tools.build:gradle:7.0.4'
          // NOTE: Do not place your application dependencies here; they belong
          // in the individual module build.gradle files
      }
    }

    task clean(type: Delete) {
        delete rootProject.buildDir
    }



// gradle(module)


    plugins {
        id 'com.android.application'
    }

    android {
        compileSdk 31

        defaultConfig {
            applicationId "com.example.project"
            minSdk 28
            targetSdk 28
            versionCode 1
            versionName "1.0"

            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
       }

     buildTypes {
         release {
             minifyEnabled false
             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
         }
     }
       compileOptions {
           sourceCompatibility JavaVersion.VERSION_1_8
           targetCompatibility JavaVersion.VERSION_1_8
       }
       buildToolsVersion '31.0.0'
       compileSdkVersion 31
    }

    dependencies {

        implementation 'androidx.appcompat:appcompat:1.4.0'
        implementation 'com.google.android.material:material:1.4.0'
        implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
        testImplementation 'junit:junit:4.13.2'
        androidTestImplementation 'androidx.test.ext:junit:1.1.3'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

        implementation 'com.github.bifan-wei:HwTxtReader:V2.2'
    }

**Comment by bifan-wei** [comment]
> > > 不好意思 試了很久還是無法正常build 請問一下 這樣該如何解決?
> > 
> > 
> > 不知道你具体是什么原因，你这样问太模糊了。确保build时网络没问题，或者直接使用implementation方式引入使用
> 
> 引入方式是依照wiki中所寫的方法引入的 build的時候確定網路沒問題
> 
> 以下是gradle file
> 
> ```
>   // Top-level build file where you can add configuration options common to all sub-projects/modules.
> buildscript {
>     repositories {
>         google()
>         mavenCentral()
>         maven { url'https://jitpack.io' }
>    }
>   dependencies {
>       classpath 'com.android.tools.build:gradle:7.0.4'
>       // NOTE: Do not place your application dependencies here; they belong
>       // in the individual module build.gradle files
>   }
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> // gradle(module)
> 
> ```
> plugins {
>     id 'com.android.application'
> }
> 
> android {
>     compileSdk 31
> 
>     defaultConfig {
>         applicationId "com.example.project"
>         minSdk 28
>         targetSdk 28
>         versionCode 1
>         versionName "1.0"
> 
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>    }
> 
>  buildTypes {
>      release {
>          minifyEnabled false
>          proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>      }
>  }
>    compileOptions {
>        sourceCompatibility JavaVersion.VERSION_1_8
>        targetCompatibility JavaVersion.VERSION_1_8
>    }
>    buildToolsVersion '31.0.0'
>    compileSdkVersion 31
> }
> 
> dependencies {
> 
>     implementation 'androidx.appcompat:appcompat:1.4.0'
>     implementation 'com.google.android.material:material:1.4.0'
>     implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
>     testImplementation 'junit:junit:4.13.2'
>     androidTestImplementation 'androidx.test.ext:junit:1.1.3'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
> 
>     implementation 'com.github.bifan-wei:HwTxtReader:V2.2'
> }
> ```

估计是配置的问题参考下这个文章 [https://blog.csdn.net/jian11058/article/details/116652630](https://blog.csdn.net/jian11058/article/details/116652630)

**Comment by young03600** [comment]
已經解決了
感謝

**解決方法:
在`settings.gradle`中加入 `maven { url'https://jitpack.io' }` 才是OK的**
